FROM python:3.10-alpine

RUN mkdir -p /api
RUN pip install --upgrade \
    --extra-index-url https://zivgitlab.uni-muenster.de/api/v4/projects/9020/packages/pypi/simple \
    --target /api \
    dcm-sip-builder-api

# base image
FROM swaggerapi/swagger-ui

# copy api-document from first stage into container
COPY --from=0 /api/dcm_sip_builder_api/openapi.yaml /openapi.yaml

# modify server-list
# RUN sed -i -e 's/localhost/<server-url>/g' /openapi.yaml
